-- 🦅 PREDADOR v371.1 - SUPABASE ARCHITECTURE SCRIPT
-- Copy and paste this into the Supabase SQL Editor to prepare your database.

-- 1. TRADES TABLE: Historical record of every execution
CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    action TEXT NOT NULL,
    symbol TEXT NOT NULL,
    confidence INT,
    price FLOAT8,
    qty FLOAT8,
    leverage INT,
    pnl FLOAT8 DEFAULT 0,
    version TEXT
);

-- 2. SYSTEM STATUS TABLE: Real-time heartbeat (Sovereign Dashboard)
CREATE TABLE IF NOT EXISTS system_status (
    version TEXT PRIMARY KEY,
    timestamp TEXT,
    pnl FLOAT8,
    trades INT,
    win_rate FLOAT8,
    entropy FLOAT8,
    shield TEXT,
    status TEXT
);

-- 3. SYSTEM LOGS TABLE: Audit trail for critical events
CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    event_type TEXT, -- SHIELD, KILL_SWITCH, ERROR, STARTUP
    message TEXT,
    asset TEXT,
    meta JSONB
);

-- 4. ENABLE RLS (Row Level Security) - Optional but recommended
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;

-- 5. CREATE PUBLIC ACCESS POLICIES (Read-Only for Dashboard)
CREATE POLICY "Public Read Access" ON trades FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON system_status FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON system_logs FOR SELECT USING (true);

-- 💡 PREDADOR TIP: You can now create a Real-time Dashboard 
-- pointing to these tables for 100% remote monitoring.
