-- ============================================================
-- 🦅 MASTER SETUP - PREDATOR v21.2 "APEX MUTATION"
-- INFRAESTRUTURA DE DADOS DE ALTA PERFORMANCE E SEGURANÇA
-- ============================================================

-- 1. BASE TABLES
CREATE TABLE IF NOT EXISTS public.trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    symbol TEXT NOT NULL,
    action TEXT NOT NULL,
    result TEXT,
    pnl NUMERIC(10, 2),
    price NUMERIC(10, 2),
    metadata JSONB,
    kinetic_energy NUMERIC(12, 8),
    z_score NUMERIC(10, 4),
    obp_score NUMERIC(10, 4),
    confidence_score NUMERIC(5, 2),
    btc_momentum NUMERIC(12, 8),
    is_correlated BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.daily_stats (
    date DATE PRIMARY KEY DEFAULT CURRENT_DATE,
    total_trades INT DEFAULT 0,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    total_pnl NUMERIC(10, 2) DEFAULT 0.0,
    avg_kinetic_energy NUMERIC(10, 6) DEFAULT 0.0,
    avg_confidence_score NUMERIC(5, 2) DEFAULT 0.0,
    max_drawdown NUMERIC(10, 2) DEFAULT 0.0,
    sync_efficiency NUMERIC(5, 2) DEFAULT 0.0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    level TEXT NOT NULL,
    module TEXT NOT NULL,
    message TEXT NOT NULL,
    data JSONB
);

-- 1.1 GENETIC VAULT (PROGENY SYSTEM)
CREATE TABLE IF NOT EXISTS public.genetics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    generation INT DEFAULT 1,
    dna JSONB NOT NULL, -- Pesos neurais e parâmetros
    fitness NUMERIC(10, 4), -- Win Rate ou Profit Factor
    parent_id BIGINT REFERENCES public.genetics(id),
    origin TEXT -- 'SENIOR_RENDER' ou 'JUNIOR_VERCEL'
);

-- 2. PERFORMANCE INDEXING (APEX TUNING)
-- Busca ultrarápida de histórico
CREATE INDEX IF NOT EXISTS idx_trades_created_at ON public.trades (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trades_symbol ON public.trades (symbol);

-- Logs em escala industrial (BRIN ocupa 95% menos espaço)
CREATE INDEX IF NOT EXISTS idx_system_logs_created_at_brin ON public.system_logs 
USING brin (created_at);

-- 3. AUTOMATION & SYNC (HOMEOS-LOGIC)
CREATE OR REPLACE FUNCTION public.sync_daily_metrics() 
RETURNS trigger 
SECURITY DEFINER 
SET search_path = public 
AS $$
BEGIN
  INSERT INTO public.daily_stats (date, total_trades, wins, losses, total_pnl)
  VALUES (
    (CURRENT_TIMESTAMP AT TIME ZONE 'UTC' AT TIME ZONE 'America/Sao_Paulo')::date,
    1,
    CASE WHEN NEW.result = 'WIN' THEN 1 ELSE 0 END,
    CASE WHEN NEW.result = 'LOSS' THEN 1 ELSE 0 END,
    NEW.pnl
  )
  ON CONFLICT (date) DO UPDATE SET
    total_trades = public.daily_stats.total_trades + 1,
    wins = public.daily_stats.wins + (CASE WHEN EXCLUDED.wins = 1 THEN 1 ELSE 0 END),
    losses = public.daily_stats.losses + (CASE WHEN EXCLUDED.losses = 1 THEN 1 ELSE 0 END),
    total_pnl = public.daily_stats.total_pnl + EXCLUDED.total_pnl,
    updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_sync_metrics ON public.trades;
CREATE TRIGGER trg_sync_metrics
AFTER INSERT ON public.trades
FOR EACH ROW EXECUTE FUNCTION public.sync_daily_metrics();

-- 4. CLEAN SECURITY (RLS APEX UNIFICATION)
-- Habilitar RLS em todas as tabelas
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;

-- Limpeza total de políticas antigas para evitar avisos do Linter
DO $$ 
DECLARE 
    pol record;
BEGIN
    FOR pol IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pol.policyname, pol.tablename);
    END LOOP;
END $$;

-- Recriação da Política Única de Leitura (Performance Máxima)
CREATE POLICY "APEX_UNIFIED_READ_TRADES" ON public.trades FOR SELECT USING (true);
CREATE POLICY "APEX_UNIFIED_READ_STATS" ON public.daily_stats FOR SELECT USING (true);
CREATE POLICY "APEX_UNIFIED_READ_LOGS" ON public.system_logs FOR SELECT USING (true);
CREATE POLICY "APEX_UNIFIED_READ_GENETICS" ON public.genetics FOR SELECT USING (true);
CREATE POLICY "APEX_UNIFIED_WRITE_GENETICS" ON public.genetics FOR INSERT WITH CHECK (true);

-- 5. INTELLIGENCE (VIEW)
DROP VIEW IF EXISTS public.nomad_health_check;
CREATE VIEW public.nomad_health_check WITH (security_invoker = true) AS
SELECT 
    date,
    total_trades,
    round((wins::numeric / NULLIF(total_trades, 0)) * 100, 2) as strike_rate,
    total_pnl as daily_pnl,
    avg_kinetic_energy as market_pressure,
    avg_confidence_score as brain_clarity,
    CASE 
        WHEN avg_confidence_score > 80 THEN 'OPTIMAL'
        WHEN avg_confidence_score > 50 THEN 'NEUTRAL'
        ELSE 'RECOVERY'
    END as market_state,
    updated_at as last_sync
FROM public.daily_stats
ORDER BY date DESC;

-- Análise final de tabelas para o planejador de consultas
ANALYZE public.trades;
ANALYZE public.daily_stats;
ANALYZE public.system_logs;

COMMENT ON TABLE public.trades IS 'PREDATOR v21.2: APEX MUTATION - Estrutura Ultrarrápida.';
