-- ============================================================
-- MASTER SETUP - PREDATOR v21.1 "NOMAD SOVEREIGN"
-- ESTADO ZERO OVERHEAD + SEGURANÇA CONSOLIDADA (v2)
-- ============================================================

-- 1. BASE TABLES & QUANTUM EXPANSION
CREATE TABLE IF NOT EXISTS public.trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    symbol TEXT NOT NULL,
    action TEXT NOT NULL,
    result TEXT,
    pnl NUMERIC(10, 2),
    price NUMERIC(10, 2),
    metadata JSONB,
    kinetic_energy NUMERIC(12, 8),
    z_score NUMERIC(10, 4),
    obp_score NUMERIC(10, 4),
    confidence_score NUMERIC(5, 2),
    btc_momentum NUMERIC(12, 8),
    is_correlated BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS public.daily_stats (
    date DATE PRIMARY KEY DEFAULT CURRENT_DATE,
    total_trades INT DEFAULT 0,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    total_pnl NUMERIC(10, 2) DEFAULT 0.0,
    avg_kinetic_energy NUMERIC(10, 6) DEFAULT 0.0,
    avg_confidence_score NUMERIC(5, 2) DEFAULT 0.0,
    max_drawdown NUMERIC(10, 2) DEFAULT 0.0,
    sync_efficiency NUMERIC(5, 2) DEFAULT 0.0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    level TEXT NOT NULL,
    module TEXT NOT NULL,
    message TEXT NOT NULL,
    data JSONB
);

-- Garantia de Colunas
ALTER TABLE public.trades ADD COLUMN IF NOT EXISTS kinetic_energy NUMERIC(12, 8);
ALTER TABLE public.trades ADD COLUMN IF NOT EXISTS z_score NUMERIC(10, 4);
ALTER TABLE public.trades ADD COLUMN IF NOT EXISTS obp_score NUMERIC(10, 4);
ALTER TABLE public.trades ADD COLUMN IF NOT EXISTS is_correlated BOOLEAN;
ALTER TABLE public.trades ADD COLUMN IF NOT EXISTS btc_momentum NUMERIC(12, 8);
ALTER TABLE public.trades ADD COLUMN IF NOT EXISTS confidence_score NUMERIC(5, 2);

-- 2. UNIFICAÇÃO DE POLÍTICAS (Performance Máxima - Zero Overhead)
ALTER TABLE public.trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_stats ENABLE ROW LEVEL SECURITY;

-- Limpeza de todas as políticas redundantes (Causa do erro PERFORMANCE)
DROP POLICY IF EXISTS "Acesso Total para API" ON public.trades;
DROP POLICY IF EXISTS "Analytics_Read_Only" ON public.trades;
DROP POLICY IF EXISTS "Nomad_Dashboard_Stream" ON public.trades;
DROP POLICY IF EXISTS "API_Write_Only" ON public.trades;
DROP POLICY IF EXISTS "Nomad_Sovereign_Stream" ON public.trades;

-- Única política soberana para Trades (SELECT público)
CREATE POLICY "Nomad_Sovereign_Stream" ON public.trades FOR SELECT TO public USING (true);

-- Limpeza de políticas redundantes em daily_stats
DROP POLICY IF EXISTS "Acesso Total Stats" ON public.daily_stats;
DROP POLICY IF EXISTS "Sovereign_Read" ON public.daily_stats;
DROP POLICY IF EXISTS "Unified_Dashboard_Read" ON public.daily_stats;

-- Única política soberana para Daily Stats (SELECT público para todos os roles)
CREATE POLICY "Sovereign_Read" ON public.daily_stats FOR SELECT TO public USING (true);

-- 3. INTELLIGENCE (VIEW) - SECURITY INVOKER
DROP VIEW IF EXISTS public.nomad_health_check;
CREATE VIEW public.nomad_health_check WITH (security_invoker = true) AS
SELECT 
    date,
    total_trades,
    round((wins::numeric / NULLIF(total_trades, 0)) * 100, 2) as strike_rate,
    total_pnl as daily_pnl,
    avg_kinetic_energy as market_pressure,
    avg_confidence_score as brain_clarity,
    CASE 
        WHEN avg_confidence_score > 80 THEN 'OPTIMAL'
        WHEN avg_confidence_score > 50 THEN 'NEUTRAL'
        ELSE 'RECOVERY'
    END as market_state,
    updated_at as last_sync
FROM public.daily_stats
ORDER BY date DESC;

-- 4. REMOÇÃO DE ÍNDICES E MANUTENÇÃO
DROP INDEX IF EXISTS idx_trades_hft_master;
DROP INDEX IF EXISTS idx_logs_chronological;
DROP INDEX IF EXISTS idx_stats_date;

ANALYZE public.trades;
ANALYZE public.daily_stats;

COMMENT ON TABLE public.trades IS 'PREDATOR v21.1: Estado Zero Overhead - Políticas Consolidadas.';
COMMENT ON TABLE public.daily_stats IS 'PREDATOR v21.1: Unificado para Performance.';


