-- ============================================================
-- SETUP DO BANCO DE DADOS - PREDATOR v13.0 SINGULARITY
-- ============================================================
-- Execute este script no "SQL Editor" do seu painel Supabase.

-- 1. Criação da Tabela de Histórico de Trades
CREATE TABLE IF NOT EXISTS trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    symbol TEXT NOT NULL,
    action TEXT NOT NULL, -- 'BUY', 'SELL', 'CLOSE'
    result TEXT,          -- 'WIN', 'LOSS'
    pnl NUMERIC(10, 2),   -- Profit/Loss do trade
    price NUMERIC(10, 2), -- Preço de execução
    metadata JSONB        -- Dados extras (confiança, estratégia, etc)
);

-- 2. Habilitar RLS (Row Level Security) para segurança
ALTER TABLE trades ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Segurança (Permitir acesso público para leitura/escrita simplificada ou restrita)
-- Como a API roda no server-side com a SERVICE_ROLE_KEY ou ANON_KEY, precisamos garantir acesso.
-- Para simplificar neste MVP, vamos permitir acesso total à key anonima, mas o ideal é restringir no futuro.

CREATE POLICY "Acesso Total para API" 
ON trades 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- 4. Tabela de Estado Diário (Opcional - para persistir stats do dia)
CREATE TABLE IF NOT EXISTS daily_stats (
    date DATE PRIMARY KEY DEFAULT CURRENT_DATE,
    total_trades INT DEFAULT 0,
    wins INT DEFAULT 0,
    losses INT DEFAULT 0,
    total_pnl NUMERIC(10, 2) DEFAULT 0.0,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE daily_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acesso Total Stats" 
ON daily_stats 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- ============================================================
-- FIM DO SCRIPT
-- ============================================================
